updated workflow

diff --git a/.github/workflows/lint_test_build_publish_release_sync_npm_textmod_node_sdk.yml b/.github/workflows/lint_test_build_publish_release_sync_npm_textmod_node_sdk.yml
--- a/.github/workflows/lint_test_build_publish_release_sync_npm_textmod_node_sdk.yml
+++ b/.github/workflows/lint_test_build_publish_release_sync_npm_textmod_node_sdk.yml
@@ -32,11 +32,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Get Current Version
-        run: |
-          VERSION=$(node -p "require('./package.json').version")
-          echo "VERSION=$VERSION >> $GITHUB_ENV"
-
       - name: Set up Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
@@ -60,50 +55,73 @@ jobs:
         run: npm run build
 
 
-  non-parallel-job:
+  version_package_publish_release_sync_npm:
+
     runs-on: ubuntu-latest
     needs: lint_test_build
     steps:
-      - name: Step 1
-        run: echo "Hello from non-parallel job, step 1!"
-      - name: Step 2
-        run: echo "Hello from non-parallel job, step 2!"
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      # - name: Bump Version
-      #   id: bump_version
-      #   run: |
-      #     npm install --save-dev semver
-      #     NEW_VERSION=$(node -e "const semver = require('semver'); console.log(semver.inc('${{ env.PREVIOUS_VERSION }}', '${{ github.event.inputs.version }}'))")
-      #     echo "::set-output name=new_version::$NEW_VERSION"
-      #   env:
-      #     PREVIOUS_VERSION: ${{ env.VERSION }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+          registry-url: 'https://npm.pkg.github.com'
+          always-auth: true
+          scope: '@textmod'
+        env:
+            NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}
 
-      # - name: Tag Release
-      #   id: tag
-      #   run: |
-      #     git config --local user.email "action@github.com"
-      #     git config --local user.name "GitHub Action"
-      #     git tag -a v${{ env.VERSION }} -m "Version v${{ env.VERSION }}"
-      #     echo "::set-output name=tag::v${{ env.VERSION }}"
-      #   env:
-      #     VERSION: ${{ steps.bump_version.outputs.new_version }}
+      - name: Install dependencies
+        run: npm install
 
-      # - name: Publish to GitHub Packages
-      #   run: |
-      #     npm publish --access public --@textmod:registry=https://npm.pkg.github.com/
+      - name: Bump version
+        run: |
+          npm version patch --no-git-tag-version
+          echo "VERSION=$(npm version | sed 's/.* //' | sed 's/.$//')" >> $GITHUB_ENV
 
-      # - name: Create GitHub Release
-      #   uses: actions/create-release@v1
-      #   env:
-      #     GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
-      #   with:
-      #     tag_name: ${{ steps.tag.outputs.tag }}
-      #     release_name: Release ${{ steps.tag.outputs.tag }}
-      #     body: Release ${{ steps.tag.outputs.tag }}
-      #     draft: false
-      #     prerelease: false
+      - name: Create commit
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "GitHub Actions"
+          git commit -am "Bump version to $VERSION" || (git reset HEAD~1 && exit 1)
 
-      # # - name: Sync with NPM
-      # #   uses: JS-DevTools/npm-publish@v2
-      # #   with:
-      # #     token: ${{ env.NPM_TOKEN }}
+      - name: Create tag
+        run: |
+          git tag $VERSION || (git tag -d $VERSION && exit 1)
+          git push origin $VERSION || (git push --delete origin $VERSION && exit 1)
+
+      - name: Publish to GitHub Packages
+        run: |
+          npm publish --access public --@textmod:registry=https://npm.pkg.github.com/
+
+      - name: Create release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
+        with:
+          tag_name: $VERSION
+          release_name: Release $VERSION
+          body: |
+            Release $VERSION
+          draft: false
+          prerelease: false
+
+      - name: Sync with NPM
+        uses: JS-DevTools/npm-publish@v2
+        with:
+          registry: 'https://registry.npmjs.org'
+          token: ${{ env.NPM_TOKEN }}
+
+      - name: Error handling
+        if: ${{ failure() }}
+        run: |
+          echo "An error occurred"
+          git reset HEAD~1
+          git tag -d $VERSION
+          git push --delete origin $VERSION
+          npm unpublish @textmod/$PACKAGE_NAME@$VERSION --registry=https://npm.pkg.github.com/
+          npm unpublish $PACKAGE_NAME@$VERSION --registry=https://registry.npmjs.org/ --force --token $NPM_TOKEN
+          exit 1
